### ISSUE TITLE
How to run simulation?

### ISSUE THREAD

**Issue by james-yoo** [ViWalkerDev/nanomap_ros#1]
Thank you for releasing great work! Could you please provide detail guide for running simulation?
Provided launch script only brings up joy-node for control.

**Comment by james-yoo** [comment]
ping @ViWalkerDev

**Comment by ViWalkerDev** [comment]
Hi there,

Sorry for the delay.

Yes the launch file only launches the joy node. To run a simulation you need to instantiate a simulation manager, and then provide it with a poses to simulate. In the case of the joySim, this pose incrementing is handled using the joystick topic published by the joynode launched with the launch script. In the case of poseSim, the pose is expected to be provided via a topic that you define. 

In these cases you run the simulation by running these nodes. For example. 

ros2 run nanomap_ros joySim /path_to_sim_config_file 
and then you launch the joynode.

OR

ros2 run nanomap_ros poseSim /path_to_sim_config_file /agent_pose_topic

Note, that you do not need these ros nodes for simulating if you don't want to use ROS and have another way to get your pose information. these were just for providing examples. If you look at the source for these nodes you will see that they are simply wrappers for getting a pose or pose increment and then supplying it to the underlying nanomap sim manager. 

I hope this helps. 

Cheers!
